### ISSUE TITLE
[1.12.2] Mob Properties Randomness not allowing over max cap with this mod installed

### ISSUE THREAD

**Issue by SlimefrogSocial** [Darkhax-Minecraft/AttributeFix#10]
Hello! I seem to be having an issue with either this mod or another. I have a mod called Mob Properties Randomness that allows me to set mob attributes. I have set a few dragons over the 30 armor limit. 1 in particular I gave hundreds of armor points so it will be basically untouchable. The problem is it seems to be taking just as much damage as all the rest of the dragons. It seems like this mod isn't actually overriding the armor max cap. Note that I am also adjusting the armor toughness over its max. Is there a setting I need to turn on on this mod to make it actually override it or will it do it as soon as I put it in the world? Also I saw in the config that the maxes can be set there, but as default it is already set to like 600 or 6000 and something for armor. I have only given the dragon 250 then 500 for testing to see if it changes at all by doubling the armor points, so it should be within the amount in the config.
Config for this mod is whatever the default load is.
Config for the other mod:
[MobsPropertiesRandomness.zip](https://github.com/Darkhax-Minecraft/AttributeFix/files/5548069/MobsPropertiesRandomness.zip)

**Comment by SlimefrogSocial** [comment]
Hi just wanted to put another note here if you may have been busy or something when last one was posted. I am currently facing unrelated corruption issues in the server so I have been slacking on this issue...

**Comment by Darkhax** [comment]
Hello, changing the armor stat itself above 30 usually doesn't do very much. It primarily benefits niche mod interactions. There are no config options to change the default formula and I have no plans to add such a feature at this time. Armor Toughness is also only useful in limited circumstances.

**Comment by SlimefrogSocial** [comment]
So, the dragon was getting all its armor points they were just not doing anything? Ok that makes more sense, but how may I make the dragon "untouchable?"
