### ISSUE TITLE
[1.16.5] Suggestion: Add a check for FakePlayer Class

### ISSUE THREAD

**Issue by Cixon** [Darkhax-Minecraft/AttributeFix#11]
**Context:** I use a japanese mod called [LittleMaidReBirth](https://forum.civa.jp/viewtopic.php?f=3&t=119) which adds battlemaids into minecraft. I also use this mod in-conjunction with [AnnointedItems](https://www.curseforge.com/minecraft/mc-mods/anointed-items) which adds attributes to items via an Annointed table.

My issue is that the attributes do not apply to the maids. That mod uses the class FakePlayer which extends to ServerPlayerEntity.
If AttributeFix could apply this class to its mod, I'd hope to see speedy fast maids and other cool attribute modified modded entities that also use this class!

Thank you!

Link to Maid mod(s)
Requirement [1](https://www.dropbox.com/sh/dyvk8hwkejl22qh/AABjtFko9SHBMRorrK8V2zXra/LMML-Forge-1.16.x?dl=0&preview=LMML-Forge-1.16.4-2.3.10.jar&subfolder_nav_tracking=1) & [2](https://www.dropbox.com/sh/qw3xwgupau2jhb0/AACWYqA7ZBZJjHBLzt-NPSFYa/LMRB-Forge-1.16.x?dl=0&preview=LMRB-Forge-1.16.4-2.4.1.jar&subfolder_nav_tracking=1)
_(I know, site is in japanese so here's a link to the downloads.)_

**Comment by Darkhax** [comment]
This mod doesn't care about the entity type at all. It affects the concept of attributes themselves in a way that does not have any context or association to the entities the attributes are being applied to.

**Comment by Cixon** [comment]
Which mod is this? That way I can report this attribute issue elsewhere
