### ISSUE TITLE
1.12.2 not working

### ISSUE THREAD

**Issue by VValkar** [Darkhax-Minecraft/AttributeFix#13]
I am having a issue that the mod is not working, not changing anything. I have it installed and tested it many times and i get the same damage (-4 hearts) when i am wearing 30 armor and 80 armor.I have newest version of forge 1.12.2 and this mod and some other mods.
Edit:To get that 80 armor i was using mod called materialchanger.

**Comment by Darkhax** [comment]
Closing because this question was answered on Discord.
