### ISSUE TITLE
[Requast] Save max health

### ISSUE THREAD

**Issue by ZephaniahNoah** [Darkhax-Minecraft/AttributeFix#14]
When the Attribute `generic.max_health` is used to raise the player's health above max then the player saves or logs out the players health isn't saved. Instead it is capped at ten hearts. I found [this plugin](https://www.curseforge.com/minecraft/bukkit-plugins/remember-health) which fixes this. But I wish there were a forge mod for this.

**Comment by Darkhax** [comment]
Thanks for the suggestion. I will look into this. Which MC version are you using?

**Comment by ZephaniahNoah** [comment]
1.16.5

**Comment by Darkhax** [comment]
I've made a new mod to fix this specific issue. You can find it here. https://www.curseforge.com/minecraft/mc-mods/max-health-fix
