### ISSUE TITLE
[Conflict] {attribute-fix-fabric-1.17.1-1.0.2} Origins mod armor issue

### ISSUE THREAD

**Issue by DavidGodinho** [Darkhax-Minecraft/AttributeFix#17]
When using together with Shulk Origin from Origins, the armor value goes down as the armor increases, making you take more damage.

My issue happens when putting on armor as a shulk race, tested with a full iron set vs just having no armor. Having no armor still reduces damage (from natural armor +8) whilst wearing armor made it take more damage than what the weapon would normally do (lost 4 hearts vs a 6.5 damage sword). The iron armor was crafted using the blacksmith class from Origins:Classes. When using the same armor with other races, the armor seemed to be working fine.

**Comment by Darkhax** [comment]
I haven't been able to reproduce this issue locally. Perhaps it's fixed by the Origins mod? 

Regardless, this mod doesn't touch any code that should break the Origins mod. If it is causing issues there are faulty issues somewhere in their code.
