### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Invisible229** [Darkhax-Minecraft/AttributeFix#21]
The cost of booking and its cost and restrictions remained the same, despite the established measures of the maskum and the installation of the mod did not affect this. I tried to change the config, the problem remained the same

**Comment by Invisible229** [comment]
*1.17.1

**Comment by Darkhax** [comment]
Hello, I do not understand the issue you are trying to describe. This mod does not have anything to do with books or costs. If you are trying to verify that the mod is working correctly this is what I do. 

The following command will create a Cow with 10,000 health. 
```
/summon cow ~ ~ ~ {Health:10000f,Attributes:[{Name:generic.max_health,Base:10000}]}
```

This command creates a sword that does 1,000 damage.
```
/give @p wooden_sword{AttributeModifiers:[{AttributeName:"generic.attack_damage",Amount:1000,Slot:mainhand,Name:"generic.attack_damage",UUID:[I;-12203,5348,143545,-10696]}]} 1
```

When you attack the Cow with the sword it should require 10 attacks to kill the cow (10 x 1,000 = 10,000) but it actually takes two hits. This is because the health attribute is limited to 1024 so the Cow's health is lowered to this limit. If AttributeFix is installed it will take 10 hits as intended.

**Comment by Invisible229** [comment]
hello, took screenshots showing that the player has a maximum of only 30 armor with a limit of 4000 armor with this mod. how to fix?
https://sun9-61.userapi.com/impg/y43fRR3omMCUhjzLsRlI6AjZc4Anr94HROxugA/E9Sja2Sn9nQ.jpg?size=507x229&quality=96&sign=8dac8769bf7b73a03b004e913f0acc43&type=album

https://sun9-26.userapi.com/impg/o5mBEJA4t3vKmobGDExALXTp8W7KXVK5nNqm2Q/CcOACEOtL8Q.jpg?size=1280x720&quality=96&sign=af57df60638ff090b51a9a02609c387f&type=album

https://sun9-58.userapi.com/impg/dNUdgn78lBjrmEcjlAHG3eQSdU6vER9hDhgC2A/XJCMJGwUhsM.jpg?size=1280x661&quality=96&sign=6a6ab442c6c9bfff3e22ebe74a3de58a&type=album

https://sun9-63.userapi.com/impg/LGvId9gMl6ctnPMeTljE3aNvusyRlmKktCOymQ/7syhYuX9HRQ.jpg?size=1280x720&quality=96&sign=663119465dcd0b9d0f13276a0434b4aa&type=album

<<Крипер>>= creeper
<<Броня>>=armor

The screenshot from the hp shows that there are no problems with it and with other attributes and only armor does not work!

**Comment by Darkhax** [comment]
The armor values are still being uncapped however the formula used for damage calculations does not consider armor values beyond 30. Changing the formula would rebalance the game which is out of scope for this mod. There are many other mods which use AttributeFix as a dependency to change the formula and you can look into using those mods.

**Comment by Invisible229** [comment]
can you give an example of such a mod? However, I am not in the business of creating mods via .class, javascript, only saw what it looks like. But isn't it that this upgrade beats your capabilities (changing the armor argument and taking damage)? Why not add that?

**Comment by Invisible229** [comment]
> Значения брони все еще не ограничены, однако формула, используемая для расчета урона, не учитывает значения брони выше 30. Изменение формулы к изменению баланса игры, что выходит за рамки этой моды. Есть много других модов, используют которые AttributeFix в зависимости для формулы, и вы можете изучить их использование.

I looked at 1.16.5 (in the event of a conflict of some arguments and mods, switched to 1.16) there are few mods with armor, and I understand that what I need is not there everywhere the same error: terra craft, and mob armor, divain rpg he is very good big...

**Comment by Invisible229** [comment]
the same error everywhere
