### ISSUE TITLE
[Suggestion] Extended Cap for Saturation and Hunger

### ISSUE THREAD

**Issue by rxay579** [Darkhax-Minecraft/AttributeFix#24]
Some vanilla and modded foods can lead to reaching maximum saturation before hunger is full, wasting the excess saturation.
I'm not sure if it's possible to decouple hunger and saturation, if extending these attributes would lead to unintended consequences, or if extending these attributes is possible, but these seem like nice options to have if available.

A vanilla example would be starting at zero hunger and eating Golden Carrots until hunger is full.
An extreme example of modded foods with high values would be the Confit Byaldi and Potato Knishes from the Rats mod (something like 50 hunger and 1000 saturation).

**Comment by Darkhax** [comment]
Hello, 

Thanks for the suggestion. Hunger and Saturation are not attributes or related to the attribute system so this is out of scope for this mod. There are other mods that deal with the issue you're describing however I don't know the names of any modern/updated ones.
