### ISSUE TITLE
AttributeFix Is Causing My Mod To Crash

### ISSUE THREAD

**Issue by GodMeykr** [Darkhax-Minecraft/AttributeFix#25]
AttributeFix Is Crashing My Mod, But My Mod Uses AttributeFix As A Required Dependency Because Some Of The Items In The Mod Go Well Over The Vanilla Limits.

Here Is The Crash Log:
[2022-04-03-4.log](https://github.com/Darkhax-Minecraft/AttributeFix/files/8405184/2022-04-03-4.log)

And Here Is The Debug Log:
[debug-5.log](https://github.com/Darkhax-Minecraft/AttributeFix/files/8405185/debug-5.log)

**Comment by GodMeykr** [comment]
i uploaded the wrong log

**Comment by GodMeykr** [comment]
uploaded the correct logs

**Comment by Darkhax** [comment]
> net.minecraftforge.fml.ModLoadingException: Mod chemcraft requires attributefix 0 or above
> Currently, attributefix is not installed

The attributefix mod is not installed, so it can not be the source of these issues.
