### ISSUE TITLE
AttributeFix Crashing Modpack

### ISSUE THREAD

**Issue by 0ceanM4n** [Darkhax-Minecraft/AttributeFix#28]
[crash-2022-06-03_16.56.49-fml.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/8835423/crash-2022-06-03_16.56.49-fml.txt)
![Mod Crash](https://user-images.githubusercontent.com/106840799/171942853-781bd953-718d-4256-8242-ae79043692c5.png)

**Comment by Darkhax** [comment]
This issue is caused by the config file failing to generate or being improperly modified. Please delete the attribute fix config file from the config folder and try again.

**Comment by 0ceanM4n** [comment]
it fixed, thank you!
