### ISSUE TITLE
How to modify properties using directives?

### ISSUE THREAD

**Issue by KaSock** [Darkhax-Minecraft/AttributeFix#29]
How to modify properties using directives?

**Comment by AciDawa** [comment]
you can up max hp and max armor with attributefix on forge but it's doesn't work on serveur
https://www.curseforge.com/minecraft/mc-mods/attributefix

**Comment by Darkhax** [comment]
This mod simply raises the maximum value allowed for attributes, it does not provide tools for changing those values though. You can change attribute values using things like vanilla commands, item NBT values, and other mods.
