### ISSUE TITLE
Suggestion: A readme type file that explains the config file explaining the config file. 

### ISSUE THREAD

**Issue by Nicon4454** [Darkhax-Minecraft/AttributeFix#31]
A readme type file that explains the config file explaining the config file.

**Comment by Darkhax** [comment]
The config file is pretty self explanatory. Vanilla limits attribute values to fit within a given range, for example they limit mobs to 1024 max health. The point of this mod is to replace those limits with higher ones, and the config simply allows users to replace the limits I define with their own. 

Modifying the config value is not required to use this mod, nor is it recommended. It's specifically for advanced cases. Those with a genuine need to change these properties beyond the default are expected to know how vanilla attributes work and have a decent idea of what they're trying to change.
