### ISSUE TITLE
Crashes on load - Fabric - 1.19.3

### ISSUE THREAD

**Issue by SleepyCatten** [Darkhax-Minecraft/AttributeFix#32]
Crash report - https://gist.github.com/SleepyCatten/b0f7656aa777ca471d265a5ada8561b1
(occurred with other mods installed)

Latest log - https://gist.github.com/SleepyCatten/d0adcc97414f43f3e14033fb1740bdf5
(other mods removed)

**Comment by Darkhax** [comment]
Hello,

This mod has not been ported to 1.19.3 yet, and1.19.2 files are largely not compatible with 1.19.3. I will have an update soon but haven't had much time for mod development during the holiday season.
