### ISSUE TITLE
[1.19.2] max attribute not working

### ISSUE THREAD

**Issue by itsdinkd** [Darkhax-Minecraft/AttributeFix#34]
![image](https://user-images.githubusercontent.com/35115304/215358404-3f9066f1-da7c-4375-8168-e4290d8b349f.png)

As shown in config, the max value is 10k however in game they cap at 1024.

![image](https://user-images.githubusercontent.com/35115304/215358422-40d457ce-e424-4d87-ad0c-b884640156c9.png)

this didn't happen before i ported my modpack to 1.19.2

**Comment by Darkhax** [comment]
Thanks for opening the issue report, based on your screenshot it appears the mod is working correctly? The max health is displayed as 2550 and that is the value that would be clamped to 1024 without the mod. The current health of mobs is not affected by this mod and is related to how the mob is spawned, and how custom attribute modifiers are being applied. Here is a command for a spawn egg that should spawn a zombie with 10,000 for both values.

`/give @p zombie_spawn_egg{EntityTag:{id:zombie,Health:10000,Attributes:[{Name:"generic.max_health",Base:10000f}]},display:{Name:'[{"text":"10k Health Egg","italic":false}]'}} 1`

**Comment by itsdinkd** [comment]
Hmm I see what you're saying. So I most likely have a confliction somewhere preventing the mob to have max health. It used to spawn with full hp, at least until I ported to 1.19.2

**Comment by Darkhax** [comment]
It could be a number of things and really depends on how you are spawning the mobs. For example health is loaded before the max health when using NBT. This is why my example command above sets the base health and the max health.
