### ISSUE TITLE
Version for 1.19-rc2 is marked on CurseForge as 1.18.2

### ISSUE THREAD

**Issue by Shoes4Clues** [Darkhax-Minecraft/AttributeFix#37]
Upon launch, it gives the following message as an error:
Mod 'Additionalentityattributes' (additionalentityattributes) 1.0.0+1.19 requires version 1.19-rc.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!

**Comment by Shoes4Clues** [comment]
Bugged version is AttributeFix-Fabric-1.18.2-14.0.2.jar

**Comment by Shoes4Clues** [comment]
Purely visual. Works just fine.

**Comment by Darkhax** [comment]
This mod is not called Additional Entity Attributes. There are no RC versions for this mod.
