### ISSUE TITLE
[Quilt] Crashing on anything above 17.1.3

### ISSUE THREAD

**Issue by greensad** [Darkhax-Minecraft/AttributeFix#38]
Log: https://paste.ee/p/qL96r

17.1.3 works fine but anything above this version crashes the game on launch.

**Comment by Darkhax** [comment]
Just tested this out and 17.2.6 works perfectly fine. Your crash log shows an error with the create mod that is crashing.

**Comment by greensad** [comment]
> Just tested this out and 17.2.6 works perfectly fine. Your crash log shows an error with the create mod that is crashing.

It might be a create incompatibility then because removing attributefix fixes the issue.

**Comment by Darkhax** [comment]
I've also tried loading the mod with Create and it works fine. I would recommend checking for an update to Create or one of it's addons/dependencies. If nothing needs updates try reporting the issue to Create, since this crash is coming from their code they will likely be more helpful.

**Comment by greensad** [comment]
I'm on the latest 961 ver of create, the only dependency being fabric API (or in my case qfapi which is the latest ver for 19.2) with 17.2.6 of attributefix the game crashes, using 17.1.3 the game does not crash with the same configuration. I guess something that was changed between versions is causing some kind of incompatibility with create. If you're saying it works fine with create on quilt then there must be an additional incompatibility.

**Comment by Darkhax** [comment]
I've only tested on Fabric because that is what your issue was labelled. Looking at the changes since 17.1.3, AttributeFix has not changed in any substantial way since then, just some changes to the config and mod logo file in Mod Menu. This sounds like a race condition in Create, so I would definitely report it there.
