### ISSUE TITLE
1.20 doesn't work on 1.20.1

### ISSUE THREAD

**Issue by Tapacywka** [Darkhax-Minecraft/AttributeFix#41]

**Comment by Darkhax** [comment]
Yes, that's because 1.20 and 1.20.1 are different versions. I will have official 1.20.1 versions soon.

**Comment by PEKKAMC** [comment]
when will 1.20.1 release?

**Comment by OBS3SS1ON** [comment]
- Replace mod 'AttributeFix' (attributefix) 20.0.1 with any version that is compatible with:
		 - minecraft 1.20.1
	 - Replace mod 'MaxHealthFix' (maxhealthfix) 11.0.2 with any version that is compatible with:
		 - minecraft 1.20.1
