### ISSUE TITLE
When will we get a 1.20.1 version?

### ISSUE THREAD

**Issue by TheScienceNerd** [Darkhax-Minecraft/AttributeFix#42]
I've been looking around for ways of seeing if I can get the 1.20 port to work for 1.20.1 since the _Overloaded Armor Bar_ mod I got will not let me open Minecraft until I have a working version of this mod for 1.20.1, and this is the closest I can get, being just 1.20.
I saw you said there will be a 1.20.1 version posted _soon_ about 3 weeks ago, but nothing since.
Any idea or words on any progress on that?

**Comment by Darkhax** [comment]
Sorry, I couldn't get to it before I started moving into a new apartment. Everything should be on 1.20.1 now though. https://www.curseforge.com/minecraft/mc-mods/attributefix/files?version=1.20.1
