### ISSUE TITLE
Downloading the 1.20.1 version suddenly started making all my other mods cause java.lang.RuntimeException

### ISSUE THREAD

**Issue by TheScienceNerd** [Darkhax-Minecraft/AttributeFix#43]
Before I installed the new version, everything worked fine and I was on my world and had 0 issues.
Then I saw the update so I installed the mod and the DetailedArmorBar which is why I needed the updated mod.

After I installed it, multiple mods that worked fine hours ago, started causing java.lang.RuntimeException no matter what combination of taking them out or taking out this mod and I just cannot get back into my world again after being on it hours before.

The only change was downloading this mod and suddenly everything starts breaking.

**Comment by Darkhax** [comment]
Please include the full crash log.

**Comment by TheScienceNerd** [comment]
Which one, cause I have tons from trying to remove mods to get it to actually load up once.
Went mod after mod of crashing the launcher. At 9 pm they were working fin, then by 10 pm after I downloaded this mod, everything started breaking

[crash-2023-07-17_00.05.52-client.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12066077/crash-2023-07-17_00.05.52-client.txt)
[crash-2023-07-17_00.06.19-client.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12066078/crash-2023-07-17_00.06.19-client.txt)
[crash-2023-07-17_00.06.49-client.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12066079/crash-2023-07-17_00.06.49-client.txt)
[crash-2023-07-17_00.07.21-client.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12066080/crash-2023-07-17_00.07.21-client.txt)
[crash-2023-07-17_00.09.58-client.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12066081/crash-2023-07-17_00.09.58-client.txt)
[crash-2023-07-17_00.12.45-client.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12066082/crash-2023-07-17_00.12.45-client.txt)
[crash-2023-07-17_00.19.38-client.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12066083/crash-2023-07-17_00.19.38-client.txt)
[crash-2023-07-17_00.37.36-client.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12066084/crash-2023-07-17_00.37.36-client.txt)

**Comment by Darkhax** [comment]
Just the most recent log would have been enough. The log files show pretty clearly what is wrong with your game. The mod `overloadedarmorbar` has an invalid mixin that is breaking any other mods that are related to rendering HUDs. AttributeFix or any of my other mods have nothing to do with this error.

**Comment by TheScienceNerd** [comment]
Thank you very much, I don't even remember getting that mod cause I was looking at the Detailed Armor Bar mod so I never would have seen that one. Now its all working again.
Thank you very much.
