### ISSUE TITLE
Can't connect to server with Attributefix Fabric even though I have the mod on Fabric

### ISSUE THREAD

**Issue by remidu64** [Darkhax-Minecraft/AttributeFix#44]
My friend and I are playing on a server with attributefix Fabric installed.
He plays on forge and can perfectly connect
I play on Fabric and I can't connect
I have no idea why I can't connect
This started happening from the moment we installed attributefix.

[Server Logs.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12244268/Server.Logs.txt)
[My Logs.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12244267/My.Logs.txt)
[Friend's Logs.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/12244305/Friend.s.Logs.txt)

**Comment by Darkhax** [comment]
Hello, based on the `My Logs.txt` file you don't have the AttributeFix mod installed. It's possible you were mistaken about having it installed or installed the mod to the wrong location. The connection errors in the logs also have no evidence that directly links back to AttributeFix causing an issue here. You should try installing AttributeFix and any other mods you may have forgotten again and then try reconnecting the server.

**Comment by remidu64** [comment]
Okay I will check the mod folder.

**Comment by remidu64** [comment]
I reinstalled the mod and I was able to connect.
Thanks!

**Comment by Darkhax** [comment]
Nice, glad you were able to figure it out.
