### ISSUE TITLE
Massive Lag When Near High Attribute Entities

### ISSUE THREAD

**Issue by AwesomeSavage** [Darkhax-Minecraft/AttributeFix#45]
When I go within a specific distance of entities with attributes (mainly health) over about 100000, I get a massive lag spike and can barely move until I'm out of the radius. It also doesn't help that the mobs are immune to projectiles, but that's more of a me problem.

I don't know why the spike happens, and I cannot find anything about it, plus my game has crashed a lot due to this in the past. I tried to use the greatest graphics settings I could, but even with optifine, I still got the spike. I need help with this.

**Comment by AwesomeSavage** [comment]
Also I tried essentially every lag fix I could find. They did not work.

**Comment by AwesomeSavage** [comment]
I'm on 1.19.4, but I've had this problem on many other versions.

**Comment by Quantum-mutnauQ** [comment]
Hello,
Do you use the forge or the fabric version?

**Comment by Darkhax** [comment]
Sorry for not responding, I've been looking into the issue and testing on Forge and Fabric servers for multiple versions and have not been able to confirm your issue. This mod doesn't have any continuous logic so it isn't really possible for it to cause TPS or FPS lag. I am assuming another mod was causing the lag and it was a coincidence, or they have code which is not optimized for higher attribute values, for example a health mod rendering out thousands of hearts for the health bar.
