### ISSUE TITLE
[Crash] Fabric-1.20.1-21.0.2

### ISSUE THREAD

**Issue by Phoupraw** [Darkhax-Minecraft/AttributeFix#46]
First run: [latest.log](https://github.com/Darkhax-Minecraft/AttributeFix/files/13215237/latest.log)
Second and third run: [latest.log](https://github.com/Darkhax-Minecraft/AttributeFix/files/13215246/latest.log)
There is no crash report.

**Comment by Darkhax** [comment]
Based on the first log your config file for this mod is invalid. Please delete and regenerate the config and try again.

**Comment by Phoupraw** [comment]
> Based on the first log your config file for this mod is invalid. Please delete and regenerate the config and try again.

The first run log is already a log after I deleted the config and relaunched the game.

**Comment by Darkhax** [comment]
@Phoupraw Can you upload the attributefix.json config file? The error is from reading whatever is in the file. It's either incorrect or generating incorrectly.

**Comment by Phoupraw** [comment]
> @Phoupraw Can you upload the attributefix.json config file? The error is from reading whatever is in the file. It's either incorrect or generating incorrectly.

[attributefix.json](https://github.com/Darkhax-Minecraft/AttributeFix/files/13263695/attributefix.json)

The attribute, "trifle:flying_duration", is from my mod. Its max value is infinity.

**Comment by Darkhax** [comment]
Oh okay, that would explain the issue. Java's BigDecimal doesn't support infinity and NaN values. I've pushed through an update that should be compatible with your mod. Delete the config file again and let me know how it goes. https://www.curseforge.com/minecraft/mc-mods/attributefix/files/4844657

**Comment by Phoupraw** [comment]
> Oh okay, that would explain the issue. Java's BigDecimal doesn't support infinity and NaN values. I've pushed through an update that should be compatible with your mod. Delete the config file again and let me know how it goes. https://www.curseforge.com/minecraft/mc-mods/attributefix/files/4844657

[attributefix.json](https://github.com/Darkhax-Minecraft/AttributeFix/files/13265439/attributefix.json)

By the way, could you please make it not to directly crash but log it (maybe error or fatal) and regenerate it, when meeting broken config file? That would make issue tracking easier.

**Comment by Darkhax** [comment]
@Phoupraw Did the new release fix the crash you were having? There is already some protections to regenerate the config file however this issue was a different case as it couldn't generate the initial config to write so the loading could not proceed.

**Comment by Phoupraw** [comment]
> @Phoupraw Did the new release fix the crash you were having? There is already some protections to regenerate the config file however this issue was a different case as it couldn't generate the initial config to write so the loading could not proceed.

Yes, the new release fixed the crash.
