### ISSUE TITLE
[CRASH] Forge 1.19.2 Crash Upon Startup

### ISSUE THREAD

**Issue by Ikedadel** [Darkhax-Minecraft/AttributeFix#49]
### Minecraft Version

1.19.2

### Mod Version

17.2.7

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

Booted up the game as normal, just before the game finally loaded in, it gave an error as shown in the attached file below and generated a crash log.
![Screenshot_96](https://github.com/Darkhax-Minecraft/AttributeFix/assets/68084570/6c2a50c7-18e2-4172-a20c-c3ed80047990)

### Crash Log

[crash-2024-02-23_19.17.05-fml.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/14391087/crash-2024-02-23_19.17.05-fml.txt)

### Are you doing anything weird?

This issue only popped up when I removed Tough as Nails (v. 8.0.0.78 for 1.19.2 Forge) and Tough as Tweaked (v. 1.0.2 for 1.19.2 Forge) and replaced it with ColdSweat (latest ver. for 1.19.2 Forge), Thirst Was Taken(latest ver. for 1.19.2 Forge), and Thirst Was Taken Canteens(latest ver. for 1.19.2 Forge).

**Comment by OxiiGiin1** [comment]
I'm having the same issue.

**Comment by Darkhax** [comment]
Hello, it looks like your config file is broken or corrupted. Could you please upload your attributefix config file here, delete the config for your game, and then try loading the game again.

**Comment by Ikedadel** [comment]
Apologies for the delay, here's the config file. I'll report back if removing said config fixes my issues.
[attributefix.json](https://github.com/Darkhax-Minecraft/AttributeFix/files/14450789/attributefix.json)

**Comment by Ikedadel** [comment]
It does not. Here is the error it gave me + the crash log for that + the config file that was newly generated.
![lord help me](https://github.com/Darkhax-Minecraft/AttributeFix/assets/68084570/758a94f9-13f4-47c1-8ccd-d5958ff90e6e)
[crash-2024-02-29_11.32.39-fml.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/14450968/crash-2024-02-29_11.32.39-fml.txt)
[attributefix.json](https://github.com/Darkhax-Minecraft/AttributeFix/files/14451022/attributefix.json)

**Comment by Darkhax** [comment]
It looks like you're using an outdated version of the mod. Try updating to [17.2.8](https://www.curseforge.com/minecraft/mc-mods/attributefix/files/5126457) and then deleting your config file again.
