### ISSUE TITLE
[BUG] 1.20.1 Apotheosis + AttributeFix

### ISSUE THREAD

**Issue by Krimatoria** [Darkhax-Minecraft/AttributeFix#51]
### Minecraft Version

1,20,1

### Mod Version

AttributeFix-Forge-1.20.1-21.0.4.jar

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

Apotheosis-1.20.1-7.3.1.jar

> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:mining_speed' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:arrow_velocity' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:healing_received' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:draw_speed' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:ghost_health' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:prot_pierce' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:armor_pierce' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:prot_shred' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:arrow_damage' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:fire_damage' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:current_hp_damage' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:overheal' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.166] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:crit_chance' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.167] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:dodge_chance' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.167] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:cold_damage' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.167] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:crit_damage' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.167] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:life_steal' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.167] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:experience_gained' does not belong to a known attribute. This entry will be ignored.
> [29Feb2024 19:29:52.167] [Worker-ResourceReload-6/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:armor_shred' does not belong to a known attribute. This entry will be ignored.
>

**Comment by Darkhax** [comment]
Apotheosis changed the modid of their attributes from `apotheosis` to `attributeslib` so the old config entries can no longer be applied. If you haven't modified the config file yourself these errors can be safely ignored, or you can delete the config file and regenerate it with the new attribute names. If you have made changes, you will need to update the IDs in the config file to the new ones.

**Comment by Krimatoria** [comment]
> Apotheosis изменил модификацию своих атрибутов с `apotheosis`на `attributeslib`, поэтому старые записи конфигурации больше нельзя применять. Если вы сами не изменяли файл конфигурации, эти ошибки можно безопасно игнорировать или удалить файл конфигурации и создать его заново с новыми именами атрибутов. Если вы внесли изменения, вам нужно будет обновить идентификаторы в файле конфигурации на новые.

Ooo Thanks)

**Comment by Krimatoria** [comment]
> Apotheosis изменил модификацию своих атрибутов с `apotheosis`на `attributeslib`, поэтому старые записи конфигурации больше нельзя применять. Если вы сами не изменяли файл конфигурации, эти ошибки можно безопасно игнорировать или удалить файл конфигурации и создать его заново с новыми именами атрибутов. Если вы внесли изменения, вам нужно будет обновить идентификаторы в файле конфигурации на новые.

I deleted the entire config folder Apotheosis-1.20.1-7.3.1.jar
![image](https://github.com/Darkhax-Minecraft/AttributeFix/assets/106809386/712b92b7-60df-40a0-be31-d20bd3d9f19a)


It didn't help, I still get the error.

**Comment by Darkhax** [comment]
You need to delete the right file. `attributefix.json`.
