### ISSUE TITLE
[CRASH] <new bug upon complete phase 1.19.2>

### ISSUE THREAD

**Issue by Katsby25** [Darkhax-Minecraft/AttributeFix#53]
### Minecraft Version

1.19.2

### Mod Version

17.2.8

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

<img width="425" alt="屏幕截图 2024-03-17 130328" src="https://github.com/Darkhax-Minecraft/AttributeFix/assets/140131650/3240c5a5-3c1f-4d68-a143-82a8ee4e0589">

### Crash Log

[crash-2024-03-17_13.02.35-fml.txt](https://github.com/Darkhax-Minecraft/AttributeFix/files/14626258/crash-2024-03-17_13.02.35-fml.txt)

### Are you doing anything weird?

Jesus,I didn't

**Comment by Darkhax** [comment]
It looks like your config file may be corrupted. Can you please upload it here so I can look at it? Deleting the config file and running the game again should fix it unless there is a more serious issue going on.

**Comment by Katsby25** [comment]
idk where is that config file:(.The one in the "config" folder is a json file.
[attributefix.json](https://github.com/Darkhax-Minecraft/AttributeFix/files/14647266/attributefix.json)
Or somewhere in the jar file of the mod?

**Comment by Darkhax** [comment]
@Katsby25 Yes your config file appears to be corrupted. Deleting that .json file and trying again should solve your issue.
