### ISSUE TITLE
[CRASH] Crash when reading config file.

### ISSUE THREAD

**Issue by Pyll0ck** [Darkhax-Minecraft/AttributeFix#54]
### Minecraft Version

1.18.2

### Mod Version

14.0.2 ?

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

Can't even open minecraft to the main menu, immediately opens an error instead (Screenshot included). Mod is a part of a larger modpack (Prominence II (+a few mods I added myself))

![Error Screen on Loading](https://github.com/Darkhax-Minecraft/AttributeFix/assets/168793928/80c608d4-f0e4-491b-aeaf-80b263e4cfb1)

Please explain what needs to be fixed in dumb terms, just started modding and pretty useless at it. Thanks

### Crash Log

[2024-05-03-3.log](https://github.com/Darkhax-Minecraft/AttributeFix/files/15195533/2024-05-03-3.log)

**Comment by Darkhax** [comment]
Hello, it looks like there is an issue with your config file for this mod. I've backported a few related fixes and released 14.0.3 which may help you out. If updating does not fix your issue please upload your config file here so I can see what went wrong. After uploading it, you can probably just delete the config from your machine and run the game again, this will generate a new config for you that should work.

**Comment by Pyll0ck** [comment]
Is this 14.0.3? 

https://github.com/Darkhax-Minecraft/AttributeFix/blob/1.18.2/Forge/src/main/java/net/darkhax/attributefix/AttributeFixForge.java

If not, where can I find it?

**Comment by Darkhax** [comment]
No that's the raw code of the mod. You can find the download on CurseForge https://www.curseforge.com/minecraft/mc-mods/attributefix/files/5312029

**Comment by Pyll0ck** [comment]
downloaded 14.0.3, still getting the error screen

![Screenshot (2620)](https://github.com/Darkhax-Minecraft/AttributeFix/assets/168793928/0d9ee5e0-eb08-4b62-82cc-15b811a002a1)

config file:

[attributefix.json](https://github.com/Darkhax-Minecraft/AttributeFix/files/15199891/attributefix.json)

**Comment by Darkhax** [comment]
Okay yeah, your config file got corrupted. Just delete it and the game should launch fine.

**Comment by Pyll0ck** [comment]
Yep, that got it working. Thank you!
