### ISSUE TITLE
[QUESTION] <Armor Formula>

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/AttributeFix#55]
### Question

Can you provide the changed armor formula with this mod. For 1.16.5 if it matters

**Comment by Darkhax** [comment]
Hello, this mod does not change the armor formula, damage formula, or any other calculations used by the game.

**Comment by ghost** [comment]
How does it change the limit then? So if Diamond armor gave 80% damage protection(20 armor points) how much damage protection would an armor with 30 armor points give

**Comment by Darkhax** [comment]
Attribute limits are completely independent to the limits used in other parts of the game. For example the vanilla armor cap is 30 (not 20) but the armor bar in the HUD is limited to 20 points. The formula is similar, it has its own limit that is a mathematical property of the formula used and not connected to the attribute. This means that a chestplate with 100 armor points will block the same amount of damage as a chestplate with 20 armor points, and this is true with or without the AttributeFix mod.

To explain even further, attributes clamp their values to their maximum limit. So in vanilla equipping an item with 100 armor will only give you 30 armor points. If you equip two of these items the game says 100 + 100 = 30. This is what the mod fixes, it lets the value be calculated properly. It does not change the armor bar to display more than 20 points, and it does not change the formula to give an advantage to having more armor. This mod is not solely for the armor attribute and it would be out of scope to re-balance the entire combat system. 

If you want to change those other aspects of the game you should use a mod like [ArmorUnlock](https://legacy.curseforge.com/minecraft/mc-mods/armor-unlocked) or [Armor Toughness Bar](https://legacy.curseforge.com/minecraft/mc-mods/armor-toughness-bar) which are made by other modders but rely on AttributeFix to allow the implicit limits to be surpassed.
