### ISSUE TITLE
[QUESTION] When will this mod get updated to 1.21 and 1.21.1?

### ISSUE THREAD

**Issue by PEKKAMC** [Darkhax-Minecraft/AttributeFix#56]
### Question

I haven't seen this mod updated for a while now. It is one of my favorite mod. Without this mod my custom boss only has 1024 health and will be defeated in less than a minute. So please update it to 1.21/1.21.1. I really appreciate it! Thanks!

**Comment by Darkhax** [comment]
Hello, I am hoping it will be updated soon. A lot changed with the 1.21 update so it's taking longer than usual but it's getting there.
