### ISSUE TITLE
Other Attributes?

### ISSUE THREAD

**Issue by Yourname942** [Darkhax-Minecraft/AttributeFix#6]
Is there any possibility to add a maximum amount for the other attributes:
1) all other types of resistances (poison, fire, lightning?, magic, physical, etc,)
2) health regeneration rate
3) swimming speed
4) total hearts you can have (from gear, heart container items, baubles, etc)
5) prevent  adding an enchantment if it would pass the limit of [insert attribute]
 
Is there a way to become compatible with other mods that give you attributes/enchantments?

Thank you.

**Comment by Darkhax** [comment]
It's possible to add support for attributes in other mods, however they tend to provide their own way to set the range or have no range at all and accept any value.

1) None of those things are attributes in vanilla MC. I would need to know specific mods with attributes to add support for them.
2) This is also not a vanilla attribute.
3) This can be added, but it won't be very useful. 
4) This is already a feature, it's the max health attribute.
5) This is a fundamental mechanic change and is outside the scope of the mod.

**Comment by Yourname942** [comment]
[AbyssalCraft](https://www.curseforge.com/minecraft/mc-mods/abyssalcraft),
[Astral Sorcery](https://www.curseforge.com/minecraft/mc-mods/astral-sorcery),
[Defiled Lands](https://www.curseforge.com/minecraft/mc-mods/defiled-lands),
[Electroblob'z Wizardry](https://www.curseforge.com/minecraft/mc-mods/electroblobs-wizardry),
[EvilCraft](https://www.curseforge.com/minecraft/mc-mods/evilcraft),
[Fish's Undead Rising](https://www.curseforge.com/minecraft/mc-mods/fishs-undead-rising),
[LightningCraft](https://www.curseforge.com/minecraft/mc-mods/lightningcraft),
[Primitive Mobs](https://www.curseforge.com/minecraft/mc-mods/primitive-mobs),
[Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)

**Comment by Darkhax** [comment]
I checked the source code for every mod you linked, excluding Undead Rising as the source code is not public. None of the mods I checked add new attributes types and should be fully compatible with this mod already.

**Comment by pimalel233** [comment]
@Yourname942 3) If you are up to few additional things in your game, you could try checking out Better Diving as it allows your to play with some of swimming speed values.
