### ISSUE TITLE
Before and above sequence basis

### ISSUE THREAD

**Issue by Arch23-tech** [Darkhax-Minecraft/AttributeFix#62]
### Question

now a days most of us share the same concept or mod arrangement and their categories when it comes in building a fresh version with a pre-defined modlist...
 as usual we start the game with either sodium or optifne and then their fellow mods especially performance related mods.....
it is crystal clear that (attribute fix) deals with modded attribute system and here comes the real puzzle:

should we install the mods adding mobs and creatures and then regulating their attributes by installing (attribute fix) after all of them or installing (attribute fix) and then applying all the mods related to adding creatures and mobs.

to put things in summary what i want to reach for here is:
the effect of (attribute fix) will be more magical if install it before all the mods that add additionl creatures to game and then the mod applies the correct attribute environment to their stats or (attribute fix) should be installed and put above all of them to its affect to be better on gameplay?

**Comment by Darkhax** [comment]
Hello, yes I recommend including AttributeFix from the start. If a mob spawns with an invalid attribute it can affect the gameplay long term.

For example, if a mob spawns in with an invalid max health the health will be set to the maximum value allowed. If you install AttributeFix the max health will be fixed for that mob, but it can not fix the current health value and the mob would need to heal back up to the correct amount.
